export const text = {
  appName: 'Catering Nusantara',
  hero: {
    title: 'Catering Murah & Enak',
    subtitle: 'Melayani Kantor, Sekolah & Acara di Tulungagung – Kediri – Blitar',
    cta: 'Pesan via WhatsApp',
  },
  subscription: {
    title: 'Langganan Kantor & Sekolah – Menu Beda Tiap Hari',
    description: 'Makan siang bervariasi setiap hari tanpa ribet',
    packages: [
      {
        id: 1,
        name: 'Paket Sekolah',
        price: 'mulai Rp10.000/siswa',
        description: 'Menu sehat dan bergizi untuk pelajar',
        icon: 'GraduationCap',
      },
      {
        id: 2,
        name: 'Paket Kantor',
        price: 'mulai Rp15.000/karyawan',
        description: 'Menu lengkap dengan protein dan sayuran',
        icon: 'Briefcase',
      },
      {
        id: 3,
        name: 'Paket Ekonomis',
        price: 'Rp8.000/porsi',
        description: 'Hemat tapi tetap lezat dan mengenyangkan',
        icon: 'Wallet',
      },
      {
        id: 4,
        name: 'Paket Premium',
        price: 'Rp25.000/porsi',
        description: 'Menu spesial dengan pilihan premium',
        icon: 'Award',
      },
      {
        id: 5,
        name: 'Paket Rapat',
        price: 'Rp12.000/porsi',
        description: 'Cocok untuk meeting dan acara formal',
        icon: 'Users',
      },
      {
        id: 6,
        name: 'Paket Diet',
        price: 'Rp18.000/porsi',
        description: 'Menu sehat rendah kalori dan gula',
        icon: 'Heart',
      },
      {
        id: 7,
        name: 'Paket Vegetarian',
        price: 'Rp15.000/porsi',
        description: 'Menu tanpa daging dengan protein nabati',
        icon: 'Leaf',
      },
      {
        id: 8,
        name: 'Paket Acara',
        price: 'Mulai Rp20.000/porsi',
        description: 'Untuk hajatan, syukuran, dan perayaan',
        icon: 'PartyPopper',
      },
      {
        id: 9,
        name: 'Menu Harian Disesuaikan',
        price: 'Nusantara / requestable',
        description: 'Pilih menu favorit atau sesuai kebutuhan',
        icon: 'FileEdit',
      },
      {
        id: 10,
        name: 'Jadwal Mingguan',
        price: 'via WhatsApp',
        description: 'Terima jadwal menu seminggu di muka',
        icon: 'Calendar',
      },
    ],
  },
  menu: {
    title: 'Menu Favorit',
    viewAll: 'Lihat Semua Menu',
    promos: [
      {
        id: 1,
        title: 'Promo Rapat',
        price: 'Rp12.000!',
        badge: '🔥 PROMO',
      },
      {
        id: 2,
        title: 'Paket Ramadhan',
        price: 'Diskon 25%',
        badge: '🌙 SPESIAL',
      },
      {
        id: 3,
        title: 'Paket Hajatan Hemat',
        price: 'Mulai Rp15.000',
        badge: '🎉 HEMAT',
      },
    ],
  },
  services: {
    title: 'Layanan Kami',
    items: [
      { id: 1, name: 'Office Lunch', icon: 'Briefcase' },
      { id: 2, name: 'Sekolah', icon: 'GraduationCap' },
      { id: 3, name: 'Rapat', icon: 'Users' },
      { id: 4, name: 'Event Desa', icon: 'Landmark' },
      { id: 5, name: 'Aqiqah', icon: 'Baby' },
      { id: 6, name: 'Tahlil', icon: 'Heart' },
      { id: 7, name: 'Prasmanan', icon: 'Utensils' },
      { id: 8, name: 'Lainnya', icon: 'MoreHorizontal' },
    ],
  },
  testimonials: {
    title: 'Testimoni Pelanggan',
    items: [
      {
        id: 1,
        name: 'Budi Santoso',
        role: 'Kepala Sekolah SDN 1',
        text: "Anak-anak sangat suka dengan menu catering ini. Bervariasi dan selalu tepat waktu!",
        rating: 5,
      },
      {
        id: 2,
        name: 'Siti Aminah',
        role: 'HRD PT. Maju Jaya',
        text: "Sudah 2 tahun langganan untuk makan siang kantor. Pelayanan terbaik dan harga terjangkau.",
        rating: 5,
      },
      {
        id: 3,
        name: 'Hendra Wijaya',
        role: 'Panitia Acara Desa',
        text: "Pesan untuk acara desa dengan 200 porsi. Semua tamu puas dengan rasanya!",
        rating: 4,
      },
    ],
  },
  footer: {
    cta: 'Siap makan enak tiap hari? Yuk langganan sekarang!',
    ctaButton: 'Hubungi Kami',
    address: 'Jl. Pahlawan No. 123, Tulungagung, Jawa Timur',
    phone: '+62 812-3456-7890',
    email: 'info@cateringnusantara.id',
    copyright: '© 2023 Catering Nusantara. All rights reserved.',
  },
};